name: ShellCheck

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          args: -e SC2181 -e SC1091 scripts/main.sh scripts/utils.sh plugin.tmux
